
ALTER TABLE `swift-jobs`.`listings`
ADD COLUMN `employer_name` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `city` VARCHAR(100) DEFAULT NULL,
ADD COLUMN `city` VARCHAR(100) DEFAULT NULL,
ADD COLUMN `e-mail` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `phone_number` VARCHAR(20) DEFAULT NULL;
